GET http://localhost:5000/users

### 

GET http://localhost:5000/users/1

### 

POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "name": "userName", 
    "email": "user@gmail.com",
    "password": "userPassword", 
    "role": "user"
}

### 

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "email": "user@gmail.com",
    "password": "userPassword"
}

### 

GET http://localhost:5000/me 

### 

DELETE http://localhost:5000/logout

###
POST http://localhost:5000/createjobapplication
content-type: application/json  

{
    "user_id": 1, "job_id": 1
}

###
POST http://localhost:5000/changejobapplicationstatus
content-type: application/json  

{
    "jobApplicationId": 2, "new_status": "accepted"
}

###

POST http://localhost:5000/getjobapplicationbyuserid
content-type: application/json 

{
    "userId": 1
}


# ### 
# PATCH http://localhost:5000/users/2 
# Content-Type: application/json

# {
# "name": "M Ferlinss", "email": "ff@gmail.com", "role": "Staff Gojek"

# }

# ### DELETE http://localhost:5000/users/2 Content-Type: application/json

# ### POST http://localhost:5000/users/1 Content-Type: application/json

# {
# "name": "M Fikri", "email": "fikri@gmail.com", "password": "Male"

# }

### 
POST http://localhost:5000/companies 
Content-Type: application/json

{
"company_name": "Blibli", "location": "Jakarta Barat"

}

# ### GET http://localhost:5000/companies

# ### GET http://localhost:5000/companies/1

# ### DELETE http://localhost:5000/companies/3

###
POST http://localhost:5000/staffs 
Content-Type: application/json

{
"user_id": 1, "company_id": 1

}

# ### GET http://localhost:5000/staffs

# ### DELETE http://localhost:5000/staffs/1

# ### POST http://localhost:5000/job Content-Type: application/json

# {
# "staff_id": 2, "job_name": "Software Engineer", "job_type": "Full-time", "job_level": "Senior", "job_location": "New York", "job_salary": 100000, "is_hiring": true

# }

# ### GET http://localhost:5000/job